'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const generator=require('../api-backend');
const plan={title:'Trips',format:'openapi3',baseUrl:'https://api.example.com',auth:[{type:'http',scheme:'token'}],operations:[{id:'createTrip',method:'POST',path:'/trips/{id}',requiredParameters:[{name:'id',in:'path'}],bodyFields:[{name:'segments',type:'array',required:true}],authenticationRequired:true}]};
test('generated backend executes authenticated routes, validates inputs, and never accepts client credentials or target overrides',async()=>{
 const result=generator.generate(plan),dir=fs.mkdtempSync(path.join(os.tmpdir(),'kairoq-backend-'));for(const [name,content]of Object.entries(result.files))fs.writeFileSync(path.join(dir,name),content);
 const generatedModule=require(path.join(dir,'server'));assert.deepEqual(generatedModule.sanitize({refresh_token:'hidden',nested:{access_token:'hidden'},value:1}),{refresh_token:'[redacted]',nested:{access_token:'[redacted]'},value:1});const server=generatedModule.createServer({execute:async args=>{assert.equal(args.credentialName,'KAIROQ_API_TOKEN_PROVIDER');assert.equal(args.plan.baseUrl,plan.baseUrl);return{status:200,data:{saved:args.body.segments.length}};}});
 const before=process.env.BACKEND_KEY;process.env.BACKEND_KEY='synthetic-backend-key-123';await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 try{assert.equal((await fetch(base+'/api/contract')).status,401);assert.equal((await fetch(base+'/health')).status,200);const headers={'Content-Type':'application/json','X-Backend-Key':process.env.BACKEND_KEY};const send=body=>fetch(base+'/api/operations/createTrip',{method:'POST',headers,body:JSON.stringify(body)});
 assert.equal((await send({body:{segments:[]}})).status,422);assert.equal((await send({pathParams:{id:'1'},body:{segments:'wrong'}})).status,422);const response=await send({pathParams:{id:'1'},body:{segments:[]},credentialName:'ATTACK',plan:{baseUrl:'https://evil.example'}});assert.equal(response.status,200);assert.deepEqual(await response.json(),{saved:0});
 }finally{await new Promise(r=>server.close(r));if(before===undefined)delete process.env.BACKEND_KEY;else process.env.BACKEND_KEY=before;fs.rmSync(dir,{recursive:true,force:true});}
});
test('backend refuses inferred contracts and unsafe targets',()=>{assert.throws(()=>generator.generate({...plan,format:'unstructured'}),/formal/);assert.throws(()=>generator.generate({...plan,baseUrl:'http://localhost'}),/HTTPS/);});
test('TripNinja adapter uses Token authentication instead of Bearer',()=>{const before=process.env.KAIROQ_API_APPROVED_OPERATIONS;process.env.KAIROQ_API_APPROVED_OPERATIONS='api.example.com:POST:/trips/{id}';process.env.KAIROQ_API_APPROVED_WRITES=process.env.KAIROQ_API_APPROVED_OPERATIONS;process.env.KAIROQ_API_TOKEN_TEST='synthetic';try{const request=require('../api-adapter').prepare({plan,operationId:'createTrip',pathParams:{id:'1'},credentialName:'KAIROQ_API_TOKEN_TEST',approved:true,approvedWrites:true,allowedHosts:'api.example.com'});assert.equal(request.headers.Authorization,'Token synthetic');}finally{if(before===undefined)delete process.env.KAIROQ_API_APPROVED_OPERATIONS;else process.env.KAIROQ_API_APPROVED_OPERATIONS=before;delete process.env.KAIROQ_API_APPROVED_WRITES;delete process.env.KAIROQ_API_TOKEN_TEST;}});
