const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const runtime=require('../app-runtime'),release=require('../app-release');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'kairoq-release-')),id='test-release';for(const version of [1,2]){const dir=path.join(root,id,'versions',String(version));fs.mkdirSync(dir,{recursive:true});for(const n of ['index.html','styles.css','app.js'])fs.writeFileSync(path.join(dir,n),'Version '+version);fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({schema:{collections:[{name:'items',fields:[{name:'title',type:'text'}]}]},qa:{passed:true,visual_review:{passed:true,coverage:{complete:true,mode:'ai-screenshot-review'}}}}));}runtime.saveMetadata({id,kind:'fullstack',version:2,deployed_version:1,status:'live',qa:{passed:true,visual_review:{passed:true,coverage:{complete:true,mode:'ai-screenshot-review'}}}},root);return{root,id};}
test('deployment failure restores live version and rollback preserves latest draft',async()=>{const{root,id}=fixture();try{await assert.rejects(release.deploy(id,{root,check:async()=>{throw Error('failed health')}}));assert.equal(runtime.metadata(id,root).deployed_version,1);assert.equal(release.history(id,root)[0].status,'failed');await release.deploy(id,{root});assert.equal(runtime.metadata(id,root).deployed_version,2);await release.deploy(id,{root,version:1,rollback:true});const meta=runtime.metadata(id,root);assert.equal(meta.deployed_version,1);assert.equal(meta.version,2);assert.equal(release.history(id,root)[0].type,'rollback');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('rollback editing retains fields saved by a newer version',()=>{const c={fields:[{name:'title',type:'text',required:true,label:'Title'}]};assert.deepEqual(runtime.patchValues(c,{title:'Old',category:'Tools'},{title:'New'}),{title:'New',category:'Tools'});assert.throws(()=>runtime.patchValues(c,{title:'Old'},{unknown:'bad'}));});
test('release rejects missing, incomplete and fallback visual approval before changing the live version',async()=>{
 const{root,id}=fixture();try{const file=path.join(root,id,'versions','2','manifest.json'),original=JSON.parse(fs.readFileSync(file));
 for(const visual_review of [undefined,{passed:true,coverage:{complete:false,mode:'ai-screenshot-review'}},{passed:true,coverage:{complete:true,mode:'deterministic-browser-fallback'}}]){fs.writeFileSync(file,JSON.stringify({...original,qa:{passed:true,visual_review}}));await assert.rejects(release.deploy(id,{root}),/complete passing AI/);assert.equal(runtime.metadata(id,root).deployed_version,1);}
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('a checker returning false rolls back rather than recording a healthy deployment',async()=>{
 const{root,id}=fixture();try{await assert.rejects(release.deploy(id,{root,check:async()=>({passed:false})}),/did not pass/);assert.equal(runtime.metadata(id,root).deployed_version,1);assert.equal(release.history(id,root)[0].status,'failed');}finally{fs.rmSync(root,{recursive:true,force:true});}
});
