'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),http=require('http');
const assets=require('../builder-assets'),portable=require('../project-portability');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD3sAAAAASUVORK5CYII=','base64');
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'kairoq-assets-'));
function transport(url){if(url.includes('api.openverse.org'))return Promise.resolve({bytes:Buffer.from(JSON.stringify({results:[{id:'photo-1',title:'Toronto skyline',creator:'Photographer',url:'https://images.example/toronto.png',foreign_landing_url:'https://example.com/photo',license:'by',license_url:'https://creativecommons.org/licenses/by/4.0/'},{id:'bad',url:'https://example.com/bad.png',license:'by-nc'}]}))});return Promise.resolve({bytes:png,type:'image/png'});}
test('licensed image search, download, cache and immutable serving preserve provenance',async()=>{const root=temp();try{const results=await assets.search({query:'Toronto',kind:'image'},{root,read:transport});assert.equal(results.length,1);assert.equal(results[0].download_url,undefined);const a=await assets.download(results[0].id,{root,read:transport});assert.equal(a.license,'CC-BY');assert.equal(a.attribution_required,true);assert.match(a.url,/^\/builder-assets\/[a-f0-9]{64}\.png$/);assert.deepEqual(await assets.download(a.id,{root,read:()=>{throw Error('should be cached');}}),a);const server=http.createServer((req,res)=>assets.handle(req,res,root));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+server.address().port+a.url);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await r.arrayBuffer()),png);assert.equal((await fetch('http://127.0.0.1:'+server.address().port+'/builder-assets/catalog.json')).status,404);}finally{await new Promise(r=>server.close(r));}}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('automatic sourcing downloads requested assets before handing URLs to generation',async()=>{const root=temp();try{const a=await assets.prepare('Build a travel website with Toronto pictures',async()=>({assets:[{kind:'image',query:'Toronto'}]}),{auto:true},{root,read:transport});assert.equal(a.length,1);assert.ok(fs.existsSync(path.join(root,a[0].name)));assert.match(assets.instructions(a),/APPROVED LOCAL ASSETS/);const html=assets.credits({'index.html':'<body><img src="'+a[0].url+'"></body>'},a)['index.html'];assert.match(html,/Photographer/);assert.match(html,/creativecommons/);assert.equal((assets.credits({'index.html':html},a)['index.html'].match(/id="kq-asset-credits"/g)||[]).length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('unsupported assets, license-restricted results and format masquerading reject',async()=>{const root=temp();try{await assert.rejects(assets.download('../../.env',{root}),/Search/);await assert.rejects(assets.search({query:'test',kind:'script'},{root}),/Unsupported/);assert.throws(()=>assets.put(Buffer.from('<script>bad</script>'),'png',root),/format/);assert.throws(()=>assets.put(png,'svg',root),/Unsupported/);assert.throws(()=>assets.assertReferences({'index.html':'<img src="https://example.com/photo.png">'}),/local assets/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('SSRF filters block private, loopback, mapped IPv6 and literal hosts',async()=>{for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.2','172.31.1.1','::1','::ffff:127.0.0.1','fc00::1'])assert.equal(assets.privateIP(ip),true,ip);assert.equal(assets.privateIP('8.8.8.8'),false);for(const u of ['http://example.com/a','https://127.0.0.1/a','https://user:pass@example.com/a'])await assert.rejects(assets.remote(u),/public HTTPS/);});
test('Poly Haven glTF download localizes buffers and textures into immutable local files',async()=>{const root=temp();const geometry=Buffer.from(new Float32Array([0,0,0,1,0,0,0,1,0]).buffer);const read=async url=>({bytes:Buffer.from(url.endsWith('/assets?t=models')?JSON.stringify({rock_01:{name:'Rock',tags:['rock'],authors:{Artist:{}}}}):url.includes('/files/')?JSON.stringify({gltf:{'1k':{gltf:{url:'https://cdn.example/rock.gltf',size:300,include:{'mesh.bin':{url:'https://cdn.example/mesh.bin'},'color.png':{url:'https://cdn.example/color.png'}}}}}}):url.endsWith('.gltf')?JSON.stringify({asset:{version:'2.0'},buffers:[{uri:'mesh.bin',byteLength:36}],images:[{uri:'color.png'}]}):url.endsWith('.png')?png:geometry),type:url.endsWith('.png')?'image/png':'application/octet-stream'});try{const results=await assets.search({query:'rock',kind:'model'},{root,read}),a=await assets.download(results[0].id,{root,read});assert.equal(a.dependencies.length,2);const doc=JSON.parse(fs.readFileSync(path.join(root,a.name),'utf8'));assert.match(doc.buffers[0].uri,/^\/builder-assets\//);assert.match(doc.images[0].uri,/^\/builder-assets\//);assert.equal(a.provider_credit,'Powered by Poly Haven');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('ZIP exports contain CRC-checked deflated entries and reject traversal',()=>{const z=portable.zip({'index.html':Buffer.from('hello'),'assets/photo.png':png});let offset=0,entries={};while(z.readUInt32LE(offset)===0x04034b50){const compressed=z.readUInt32LE(offset+18),length=z.readUInt16LE(offset+26),name=z.toString('utf8',offset+30,offset+30+length);entries[name]=require('zlib').inflateRawSync(z.subarray(offset+30+length,offset+30+length+compressed));offset+=30+length+compressed;}assert.equal(entries['index.html'].toString(),'hello');assert.deepEqual(entries['assets/photo.png'],png);assert.equal(z.readUInt32LE(offset),0x02014b50);assert.equal(z.readUInt32LE(z.length-22),0x06054b50);assert.throws(()=>portable.zip({'../.env':'secret'}),/Invalid export/);});
test('production HTTPS transport supplies pinned address arrays for Node automatic family selection',async()=>{
 const {EventEmitter}=require('events');let connected=false;
 const lookup=async()=>[{address:'8.8.8.8',family:4},{address:'2001:4860:4860::8888',family:6}];
 const request=(url,options,callback)=>{const req=new EventEmitter();req.setTimeout=()=>req;req.destroy=e=>{req.emit('error',e);req.emit('close');};options.lookup(url.hostname,{all:true},(err,addresses)=>{assert.equal(err,null);assert.ok(Array.isArray(addresses),'Node automatic family selection requires an array');assert.deepEqual(addresses,[{address:'8.8.8.8',family:4}]);connected=true;});queueMicrotask(()=>{const res=new EventEmitter();res.statusCode=200;res.headers={'content-type':'image/png','content-length':png.length};callback(res);res.emit('data',png);res.emit('end');req.emit('close');});return req;};
 const result=await assets.remote('https://images.example/photo.png',{lookup,request});assert.equal(connected,true);assert.deepEqual(result.bytes,png);await assert.rejects(assets.remote('https://images.example/photo.png',{lookup:async()=>[{address:'127.0.0.1',family:4}],request:()=>{throw Error('must not connect');}}),/Private network/);
});
