'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const builder=require('../app-builder'),components=require('../app-components'),runtime=require('../app-runtime'),auth=require('../housing-runtime'),release=require('../app-release');
function candidate(){const schema={collections:[{name:'enquiries',label:'Enquiries',fields:[{name:'name',label:'Contact name',type:'text',required:true},{name:'status',label:'Status',type:'select',options:['new','booked'],required:true}]},{name:'tasks',label:'Tasks',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'priority',label:'Priority',type:'select',options:['normal','urgent'],required:true}]}]};return{schema,version:1,files:components.inject({'index.html':'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="styles.css"></head><body><section id="auth-view"><h1>QA desk</h1><form id="auth-form"><label>Email<input type="email" id="auth-email" required></label><label>Password<input type="password" id="auth-password" required minlength="10"></label><button id="register">Register</button><button id="login">Login</button></form></section><main id="app-view" hidden><h1>Records</h1><button id="logout">Sign out</button><label>Collection<select id="collection-select"></select></label><div id="dashboard-metrics"></div><h2 id="form-title">New record</h2><form id="record-form"><div id="record-fields"></div><button id="save-record">Save</button></form><label>Search<input id="record-search"></label><label>Status<select id="record-filter" data-field="status"></select></label><p id="record-count"></p><div id="record-list"></div></main><script src="app.js"></script></body></html>','styles.css':'body{font:16px Arial;color:#172820;background:#fff;margin:20px}label{display:block;margin:16px 0}input,select,button{font:inherit;padding:12px;max-width:100%;box-sizing:border-box}table{width:100%;min-width:720px}td,th{padding:10px}button{color:#172820;background:#eee}#dashboard-metrics{display:flex;gap:16px}#record-list{overflow:auto}main{max-width:100%}form{margin-bottom:20px}.kq-metric-value{display:block}.kq-sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}','app.js':''})};}
test('all collections and error/retry states pass the actual Chromium journey',{skip:!fs.existsSync(process.env.CHROMIUM_PATH||'/usr/bin/chromium')},async()=>{const qa=await builder.browserQA('journey-fixture',candidate(),null,{capture:true});assert.equal(qa.passed,true);assert.ok(qa.tested.some(t=>t.startsWith('tasks: UI')));assert.ok(qa.tested.some(t=>t.includes('error recovery')));assert.ok(qa._screenshots.some(s=>s.label.includes('service error')));assert.ok(qa._screenshots.some(s=>s.label==='Mobile Tasks · editing'));});
test('deployed QA checks live routes and removes only its synthetic identity',{skip:!fs.existsSync(process.env.CHROMIUM_PATH||'/usr/bin/chromium')},async()=>{const id='live-qa-'+crypto.randomBytes(5).toString('hex'),p=candidate(),folder=path.join(runtime.ROOT,id,'versions','1');p.schema.collections[0].fields.push({name:'task',label:'Linked task',type:'reference',collection:'tasks',required:true});fs.mkdirSync(folder,{recursive:true});for(const[n,c]of Object.entries(p.files))fs.writeFileSync(path.join(folder,n),c);fs.writeFileSync(path.join(folder,'manifest.json'),JSON.stringify({schema:p.schema,qa:{passed:true}}));runtime.saveMetadata({id,version:1,deployed_version:1,status:'live',data_backend:'sqlite'});const db=auth.database(runtime.ROOT,id);db.prepare('INSERT INTO users VALUES(?,?,?,?)').run('real-owner','real@example.com','salt','hash');const server=require('http').createServer(async(req,res)=>{if(req.method==='GET'&&req.url.includes('/api/collections/tasks'))await new Promise(resolve=>setTimeout(resolve,250));if(!await runtime.handle(req,res)){res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const qa=await builder.browserQA(id,p,null,{liveBase:'http://127.0.0.1:'+server.address().port+'/apps/'+id+'/'});assert.equal(qa.passed,true);assert.deepEqual(db.prepare('SELECT email FROM users').all().map(u=>u.email),['real@example.com']);}finally{await new Promise(r=>server.close(r));fs.rmSync(path.join(runtime.ROOT,id),{recursive:true,force:true});}});
test('public origin configuration rejects credentials and nonlocal HTTP',()=>{assert.equal(release.publicOrigin({RAILWAY_PUBLIC_DOMAIN:'example.up.railway.app'}),'https://example.up.railway.app');assert.throws(()=>release.publicOrigin({KAIROQ_PUBLIC_URL:'http://remote.example'}));assert.throws(()=>release.publicOrigin({KAIROQ_PUBLIC_URL:'https://user:secret@example.com'}));});
test('public website checks accept working controls and reject nested preview navigation',{skip:!fs.existsSync(process.env.CHROMIUM_PATH||'/usr/bin/chromium')},async()=>{
 const html='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px Arial;margin:20px}section{min-height:700px}button,a{padding:12px}.skip-link{position:absolute;top:-80px}.skip-link:focus{top:0}</style><a class="skip-link" href="#services">Skip to content</a><h1>PlanURstay</h1><a href="#enquire">Make an enquiry</a><section id="services"><h2>Furnished stays</h2></section><section id="enquire"><h2>Enquiry details</h2><details><summary>Where do you operate?</summary><p>Canada and USA</p></details></section>';
 const nested='<!doctype html><iframe style="width:100%;height:900px" srcdoc="'+html.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')+'"></iframe>';
 let warmingAttempts=0;const server=require('http').createServer((req,res)=>{res.setHeader('Content-Type','text/html');if(req.url==='/missing.html'){res.writeHead(404);return res.end('Missing');}if(req.url==='/multi.html'||req.url==='/bad-link.html'){res.setHeader('Content-Security-Policy',require('../website-release').CSP);return res.end(html+'<a href="'+(req.url==='/multi.html'?'next.html':'missing.html')+'">Next page</a>');}if(req.url.startsWith('/warming')&&warmingAttempts++===0){res.writeHead(503);return res.end('Starting');}res.end(req.url.startsWith('/broken')?nested:req.url.startsWith('/sandbox')?require('../design-showcase').render(html):html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 try{const verify=require('../deployed-website-qa').verify;const result=await verify(base+'/good');assert.equal(result.passed,true);assert.equal(result._screenshots.length,2);assert.equal((await verify(base+'/warming')).passed,true);assert.equal((await verify(base+'/sandbox')).passed,true);assert.ok(warmingAttempts>=2);assert.equal((await verify(base+'/multi.html')).passed,true);await assert.rejects(verify(base+'/bad-link.html'),/cross-page navigation failed/);await assert.rejects(verify(base+'/broken'),/navigation|nested|missing|Timeout/);}finally{await new Promise(r=>server.close(r));}
});

test('Travellez four-panel business dashboard survives real browser CRUD and every breakpoint',{skip:!fs.existsSync(process.env.CHROMIUM_PATH||'/usr/bin/chromium'),timeout:180000},async()=>{
 const project=candidate();
 project.schema.collections=[
  {name:'trips',label:'Trips',fields:[{name:'traveler',label:'Traveler',type:'text',required:true},{name:'status',label:'Status',type:'select',options:['planned','approved','booked'],required:true},{name:'destination',label:'Destination',type:'text',required:true}]},
  {name:'approvals',label:'Approvals',fields:[{name:'request',label:'Request',type:'text',required:true},{name:'status',label:'Status',type:'select',options:['pending','approved','rejected'],required:true}]},
  {name:'expenses',label:'Expenses',fields:[{name:'description',label:'Description',type:'text',required:true},{name:'status',label:'Status',type:'select',options:['draft','submitted','paid'],required:true},{name:'amount',label:'Amount',type:'number',required:true}]},
  {name:'travelers',label:'Travelers',fields:[{name:'full_name',label:'Full name',type:'text',required:true},{name:'status',label:'Status',type:'select',options:['active','inactive'],required:true},{name:'email',label:'Email',type:'email',required:true}]}
 ];
 const qa=await builder.browserQA('travellez-four-panels-qa',project,null,{capture:true});
 assert.equal(qa.passed,true,JSON.stringify(qa.errors||qa.findings));
 for(const group of project.schema.collections){
  assert.ok(qa.tested.some(t=>t.includes(group.name+': UI create/edit/reload/delete')),group.name+' CRUD');
  for(const width of [768,1024])assert.ok(qa.tested.some(t=>t.includes(group.name+': responsive '+width+'px')),group.name+' '+width);
  assert.ok(qa._screenshots.some(s=>s.label==='Mobile '+group.label+' · saved'),group.name+' mobile screenshot');
 }
 assert.ok(qa._screenshots.length>=24,'real screenshots must be captured');
});
