"use strict";
// Deterministic, dependency-free SDK generation. No arbitrary npm install or code execution.
const api=require("./api-learning");
function safeIdentifier(v){const s=String(v||"").replace(/[^a-z0-9_]/gi,"_").replace(/^([^a-zA-Z_])/,"_$1");return s.slice(0,90)||"operation";}
function generate(input,{language="typescript",className="KairoqApiClient"}={}){
 const plan=input?.operations?input:api.learn(input);
 if(!["typescript","javascript"].includes(language))throw Error("SDK language must be javascript or typescript");
 if(!/^[A-Z][A-Za-z0-9]{1,70}$/.test(className))throw Error("Invalid SDK class name");
 const scheme=plan.auth?.find(a=>a.type==="http")?.scheme?.toLowerCase();const prefix=scheme==="token"?"Token ":scheme==="basic"?"Basic ":"Bearer ";
 const used=new Set(),methods=[];
 for(const op of plan.operations){let name=safeIdentifier(op.id);if(used.has(name))name=name+"_"+op.method.toLowerCase();if(used.has(name))throw Error("Duplicate SDK method");used.add(name);
  const pathname=JSON.stringify(op.path),verb=JSON.stringify(op.method);
  methods.push(`  async ${name}(options = {}) {
    return this.request(${verb}, ${pathname}, options);
  }`);
 }
 const source=`"use strict";
// Generated by Kairoq from API documentation. Use server-side only.
class ${className} {
  constructor({baseUrl, token, fetchImpl = fetch}) {
    if(typeof baseUrl!=="string" || !baseUrl.startsWith("https://")) throw Error("HTTPS baseUrl required");
    this.baseUrl=baseUrl;this.token=token;this.fetchImpl=fetchImpl;
  }
  async request(method, path, {pathParams={},query={},body,signal}={}) {
    for(const [key,value] of Object.entries(pathParams)) {
      if(!/^[a-zA-Z0-9_]+$/.test(key))throw Error("Invalid path parameter");
      path=path.replace("{"+key+"}",encodeURIComponent(String(value)));
    }
    if(/[{}]/.test(path))throw Error("Missing path parameter");
    const base=new URL(this.baseUrl);
    const url=new URL(base.href.replace(/\\/$/,"")+"/"+path.replace(/^\\/+/,""));
    if(url.origin!==base.origin)throw Error("Cross-origin API target rejected");
    for(const [k,v] of Object.entries(query))url.searchParams.set(k,String(v));
    const headers={Accept:"application/json",...(this.token?{Authorization:${JSON.stringify(prefix)}+this.token}:{})};
    if(body!==undefined)headers["Content-Type"]="application/json";
    const res=await this.fetchImpl(url.href,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal,redirect:"error"});
    const raw=await res.text();let data;try{data=JSON.parse(raw);}catch{data=raw;}
    if(!res.ok){const error=new Error("API HTTP "+res.status);error.status=res.status;error.response=data;throw error;}
    return data;
  }
${methods.join("\n")}
}
module.exports={${className}};
`;
 return{language:"javascript",filename:"kairoq-api-client.js",source,operations:plan.operations.length,notes:["Server-side SDK only; supply tokens from an approved secret manager or OAuth service","Use an approved base URL and never run generated SDK code automatically","Generated client does not bypass Kairoq live-call policy"]};
}
module.exports={generate};
