'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),http=require('http');
const runtime=require('./app-runtime'),supabase=require('./supabase-builder');
const locks=new Set();
function history(id,root=runtime.ROOT){runtime.metadata(id,root);const file=path.join(root,id,'deployments.json');return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):[];}
function writeHistory(id,entry,root){const data=history(id,root);data.unshift(entry);const file=path.join(root,id,'deployments.json');const temp=file+'.tmp';fs.writeFileSync(temp,JSON.stringify(data.slice(0,100),null,2));fs.renameSync(temp,file);}
function versions(id,root=runtime.ROOT){const meta=runtime.metadata(id,root);return fs.readdirSync(path.join(root,id,'versions')).filter(n=>/^\d+$/.test(n)).map(Number).sort((a,b)=>b-a).map(version=>{const p=runtime.readVersion(id,version,root);return{version,qa:p.qa|| (version===meta.version?meta.qa:null),deployed:version===(meta.deployed_version||(meta.status==='live'?meta.version:null)),preview_url:'/apps/'+id+'/preview/'+version+'/'};});}
async function serveCheck(id,version,p,root=runtime.ROOT){const server=http.createServer(async(req,res)=>{if(root===runtime.ROOT){if(!await runtime.handle(req,res)){res.writeHead(404);res.end();}}else{const live=runtime.metadata(id,root);const active=runtime.readVersion(id,live.deployed_version,root);res.setHeader('X-Kairoq-Version',String(active.version));res.end(active.files['index.html']);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+server.address().port+'/apps/'+id+'/',{signal:AbortSignal.timeout(5000)});if(!r.ok||r.headers.get('x-kairoq-version')!==String(version)||await r.text()!==p.files['index.html'])throw Error('Deployed route failed its health check');}finally{await new Promise(r=>server.close(r));}}
async function deploy(id,{version,rollback=false,root=runtime.ROOT,check=serveCheck,cloud}={}){
 if(locks.has(id))throw Error('A deployment is already running');locks.add(id);let old,changed=false,backendChanged=false;const event={id:crypto.randomUUID(),type:rollback?'rollback':'deploy',status:'preparing',started_at:new Date().toISOString()};
 try{old=runtime.metadata(id,root);version=Number(version===undefined?old.version:version);if(!Number.isInteger(version)||version<1)throw Error('Choose a valid version');event.version=version;const candidate=runtime.readVersion(id,version,root);const qa=candidate.qa||(version===old.version?old.qa:null);if(!qa?.passed)throw Error('This version has not passed browser QA');if(qa.visual_review&&!qa.visual_review.passed)throw Error('This version needs design refinement before deployment');const previous=old.deployed_version||(old.status==='live'?old.version:null);event.previous_version=previous;
 if(old.data_backend==='supabase'){const provider=cloud||supabase.get();await provider.provision(id,candidate.schema,version);backendChanged=true;}
 const meta={...old,deployed_version:version,status:'live',published_at:new Date().toISOString(),live_url:'/apps/'+id+'/',preview_url:'/apps/'+id+'/preview/'+old.version+'/'};runtime.saveMetadata(meta,root);changed=true;await check(id,version,candidate,root);event.status='healthy';event.finished_at=new Date().toISOString();writeHistory(id,event,root);return{...runtime.metadata(id,root),url:meta.live_url,deployment:event};
 }catch(e){if(changed&&old)runtime.saveMetadata(old,root);if(backendChanged&&old){const previous=old.deployed_version||(old.status==='live'?old.version:null);if(previous)try{await(cloud||supabase.get()).provision(id,runtime.readVersion(id,previous,root).schema,previous);}catch{event.backend_recovery_required=true;}}
 event.status='failed';event.error=String(e.message).slice(0,300);event.finished_at=new Date().toISOString();if(old)writeHistory(id,event,root);throw e;
 }finally{locks.delete(id);}
}
module.exports={deploy,history,versions,serveCheck};
