"use strict";
const fs=require('fs'),path=require('path'),crypto=require('crypto'),http=require('http'),vm=require('vm');
const runtime=require('./app-runtime');
const cloud=require('./supabase-builder');
const design=require('./design-guidance');const components=require('./app-components');
const designPipeline=require('./design-pipeline'),designSystem=require('./design-system'),designDom=require('./design-dom');
const JOBS=path.join(__dirname,'workspace','build-jobs');fs.mkdirSync(JOBS,{recursive:true});
const CONTRACT=`You are building a real full-stack business app on Kairoq's managed CRUD runtime. Return ONLY JSON {project_name,summary,schema:{collections:[{name,label,fields:[{name,label,type,required,options?,default?}]}]},files:{"index.html":"complete HTML","styles.css":"complete CSS","app.js":"complete browser JS"}}.
Design an original polished responsive app matching the user's brief. Use semantic HTML, labelled forms, calm premium visual hierarchy, complete loading/error/empty states, accessible contrast and keyboard controls, safe rendering of record values through textContent. Pure HTML/CSS/JS, relative styles.css and app.js links. No external scripts, libraries, fonts or images. Choose 1–4 useful data collections for the app. Each collection and field name is lowercase snake_case. Types: text,textarea,email,number,date,boolean,select (select options are strings). Do not use reserved names id,user_id,created_at,updated_at as fields. The data model and custom UI must match the requested industry, not a housing template.
Real server API, relative fetch('api/...') with same-origin cookies:
POST api/auth/register or api/auth/login {email,password} -> {user:{id,email}}, sets HttpOnly session; password minimum10. GET api/auth/me -> {user},401 signed out. POST api/auth/logout {}.
GET api/schema -> {schema:{collections:[...]}}. GET api/dashboard -> {total,collections:{collection_name:count,...}}.
GET api/collections/NAME -> {records:[{id,data:{field_name:value,...},created_at,updated_at}]}. POST api/collections/NAME accepts a plain field object -> {record}. PATCH api/collections/NAME/ID accepts updated fields -> {record}. DELETE api/collections/NAME/ID -> {ok:true}. All records isolated by signed-in user. NEVER localStorage for users or records; use backend as authoritative.
Required UI contract for functional testing: #auth-form with #auth-email,#auth-password and submit buttons #register,#login to choose action. Show #auth-form when signed out. #logout button. When signed in show #collection-select (select with collection names as values), #record-form with each selected collection field input/select/textarea whose name equals field name, #save-record submit. Boolean fields are checkboxes. #record-count shows total records for the selected collection. Each record has data-record-id=ID and edit/delete buttons with data-action=edit/delete. Include functional create, list, edit, delete, collection navigation and dashboard. Call auth/me on startup, use schema from backend or the identical schema embedded in code. Clear invalid prior form values on collection change. No fake payments, external integrations or server functionality. Explain unsupported requested integrations briefly in summary instead of inventing success.
All files complete, total output under 11000 tokens. CSS respect reduced motion, mobile390px and desktop1440px. Required fields must be clear. Link all app sections through real in-app navigation.`;
for(const file of fs.readdirSync(JOBS)){if(!file.endsWith('.json'))continue;try{const job=JSON.parse(fs.readFileSync(path.join(JOBS,file),'utf8'));if(['queued','designing','generating','testing','repairing','reviewing','polishing'].includes(job.status)){job.status='failed';job.error='Build interrupted by a server restart. Retry the build or revision; the last working app is unchanged.';fs.writeFileSync(path.join(JOBS,file),JSON.stringify(job,null,2));}}catch{}}
function writeJob(job){fs.writeFileSync(path.join(JOBS,job.id+'.json'),JSON.stringify(job,null,2));}
function getJob(id){if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid job ID');return JSON.parse(fs.readFileSync(path.join(JOBS,id+'.json'),'utf8'));}
function normalize(result){const schema=runtime.validateSchema(result.schema),raw=result.files||result;const files=Object.fromEntries(['index.html','styles.css','app.js'].map(n=>[n,raw[n]]));for(const [n,v] of Object.entries(files))if(typeof v!=='string'||v.length>160000)throw Error('Missing or oversized file '+n);if(files['index.html'].length<500||files['styles.css'].length<500)throw Error('Incomplete app output');if(/<script\b[^>]+src=["'](?!\.?\/?app\.js["'])/i.test(files['index.html']))throw Error('External scripts are unsupported');new vm.Script(files['app.js']);return{project_name:String(result.project_name||'New App').slice(0,100),summary:String(result.summary||'').slice(0,500),schema,files};}
function normalizePolish(candidate,polished){return normalize({...candidate,files:{...candidate.files,...(polished.files||polished)}});}
function versionFolder(id,version){return path.join(runtime.ROOT,id,'versions',String(version));}
function writeVersion(id,version,p){const dir=versionFolder(id,version);fs.mkdirSync(dir,{recursive:true});for(const [n,v] of Object.entries(p.files))fs.writeFileSync(path.join(dir,n),v);fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({schema:p.schema,qa:p.qa,design_plan:p.design_plan},null,2));}
function sample(collection){return Object.fromEntries(collection.fields.map(f=>[f.name,f.default??(f.type==='boolean'?true:f.type==='number'?125:f.type==='date'?'2030-11-01':f.type==='email'?'qa@example.com':f.type==='select'?f.options[0]:'QA '+f.label)]));}
async function revealNavigationControl(page,id){
 const control=page.locator('#'+id);const box=await control.boundingBox(),width=page.viewportSize().width;
 if(await control.isVisible()&&box&&box.x+box.width>0&&box.x<width)return;
 const toggles=[];
 for(const toggle of await page.locator('button[aria-controls][aria-expanded="false"]').all())if(await toggle.isVisible()){
  const targets=await toggle.getAttribute('aria-controls');const contains=await page.evaluate(({targets,id})=>targets.split(/\s+/).some(target=>document.getElementById(target)?.contains(document.getElementById(id))),{targets,id});toggles.push({toggle,contains});
 }
 toggles.sort((a,b)=>Number(b.contains)-Number(a.contains));
 for(const {toggle}of toggles){await toggle.click();const rect=await control.boundingBox();if(await control.isVisible()&&rect&&rect.x+rect.width>0&&rect.x<width)return;}
}
async function selectCollection(page,name){
 await revealNavigationControl(page,'collection-select');await page.locator('#collection-select').selectOption(name);
 if(page.viewportSize().width>600)return;
 if(await page.locator('#kq-navigation-close').isVisible()){await page.locator('#kq-navigation-close').click();return;}
 for(const toggle of await page.locator('button[aria-controls][aria-expanded="true"]').all()){
  const targets=await toggle.getAttribute('aria-controls');
  if(await toggle.isVisible()&&await page.evaluate(targets=>targets.split(/\s+/).some(target=>document.getElementById(target)?.contains(document.getElementById('collection-select'))),targets))await toggle.click();
 }
}
async function waitForWorkspace(page,timeout=12000){
 try{await page.locator('#record-form').waitFor({state:'visible',timeout});}
 catch(e){const feedback=await page.evaluate(()=>{const messages=['auth-message','app-message'].map(id=>document.getElementById(id)?.textContent||'').filter(Boolean);for(let n=document.getElementById('record-form');n;n=n.parentElement){const css=getComputedStyle(n);if(n.hidden||css.display==='none'||css.visibility==='hidden')messages.push('Hidden ancestor: '+n.tagName+'#'+n.id+'.'+n.className);}return messages.join('; ');});throw Error(e.message+'\nApp feedback: '+(feedback||'No error feedback; check required component visibility.'));}
}
async function browserQA(id,candidate,previous,{capture=false}={}){
 const screenshots=[],designChecks=[];async function shot(page,label){if(capture){await page.evaluate(()=>window.scrollTo(0,0));designChecks.push(...await designDom.inspect(page,label));screenshots.push({label,bytes:await page.screenshot({type:"jpeg",quality:65,fullPage:true})});}}
 const temp=fs.mkdtempSync(path.join(require('os').tmpdir(),'kairoq-app-qa-')),prefix='/apps/'+id+'/';let schema=candidate.schema;
 const server=http.createServer(async(req,res)=>{const route=req.url.split('?')[0].slice(prefix.length);if(route.startsWith('api/'))return runtime.api(req,res,{root:temp,id,route:'/'+route.slice(4),schema});const file=route||'index.html';if(!candidate.files[file]){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/javascript');res.end(candidate.files[file]);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+prefix;let browser;
 try{
  const {chromium}=require('playwright-core');browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const email='qa-'+crypto.randomBytes(6).toString('hex')+'@example.com',password=crypto.randomBytes(18).toString('hex');await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());await page.goto(base);await shot(page,'Desktop login · 1440px');await page.locator('#auth-email').fill(email);await page.locator('#auth-password').fill(password);await page.locator('#register').click();await waitForWorkspace(page);
  await shot(page,'Desktop empty dashboard · 1440px');let saved,sortedTable=false;
  if(previous){const collection=previous.schema.collections[0],payload=sample(collection);saved=await page.evaluate(async({name,payload})=>{const r=await fetch('api/collections/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error('Could not seed revision regression record');return(await r.json()).record},{name:collection.name,payload});await page.reload();await waitForWorkspace(page);}
  const collection=candidate.schema.collections[0];await selectCollection(page,collection.name);const payload=sample(collection);for(const f of collection.fields){const field=page.locator('#record-form [name="'+f.name+'"]');if(f.type==='boolean')await field.setChecked(payload[f.name]);else if(f.type==='select')await field.selectOption(payload[f.name]);else await field.fill(String(payload[f.name]));}await page.locator('#save-record').click();await page.locator('[data-record-id]').first().waitFor({timeout:12000});await page.waitForFunction(async({name,payload})=>(await(await fetch('api/collections/'+name)).json()).records.some(r=>Object.entries(payload).every(([k,v])=>r.data[k]===v)),{name:collection.name,payload},{timeout:10000});
  if(await page.locator('#record-list .kq-sort-button').count()){
   const field=collection.fields[0],second={...payload};second[field.name]=field.type==='number'?Number(payload[field.name])-1:field.type==='boolean'?!payload[field.name]:field.type==='date'?'2030-10-01':field.type==='email'?'aa.qa@example.com':field.type==='select'?(field.options.find(v=>v!==payload[field.name])||payload[field.name]):'AA QA '+field.label;
   await page.evaluate(async({name,data})=>{const response=await fetch('api/collections/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw Error('Could not seed sorting regression record');},{name:collection.name,data:second});
   await page.reload();await waitForWorkspace(page);await selectCollection(page,collection.name);await page.locator('[data-record-id]').nth(1).waitFor();
   for(const direction of [1,-1]){await page.locator('#record-list .kq-sort-button').first().click();const expected=await page.evaluate(async({name,key,direction})=>(await(await fetch('api/collections/'+name)).json()).records.sort((a,b)=>direction*(typeof a.data[key]==='number'&&typeof b.data[key]==='number'?a.data[key]-b.data[key]:String(a.data[key]??'').localeCompare(String(b.data[key]??''),undefined,{numeric:true,sensitivity:'base'}))).map(r=>r.id),{name:collection.name,key:field.name,direction});const observed=await page.locator('[data-record-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.recordId));if(JSON.stringify(expected)!==JSON.stringify(observed))throw Error('Table sorting did not change visible record order');}
   sortedTable=true;
  }
  await shot(page,'Desktop populated dashboard · 1440px');
  if(collection.fields.some(f=>f.name==='category'&&f.type==='select')&&await page.locator('#category-filter').count()){const options=await page.locator('#category-filter option').evaluateAll(nodes=>nodes.map(n=>n.value));const different=options.find(v=>v&&v!==payload.category);if(different){await page.locator('#category-filter').selectOption(different);const expected=await page.evaluate(async({name,category})=>(await(await fetch('api/collections/'+name)).json()).records.filter(r=>r.data.category===category).length,{name:collection.name,category:different});if(await page.locator('[data-record-id]').count()!==expected)throw Error('Category filter failed');await page.locator('#category-filter').selectOption(options.includes('')?'':options[0]);}}
  const filter=page.locator('#app-view select[data-field]');if(await filter.count()===1){const name=await filter.getAttribute('data-field'),field=collection.fields.find(f=>f.name===name);if(field?.type==='select'){for(const value of field.options){await filter.selectOption(value);const expected=await page.evaluate(async({collection,name,value})=>(await(await fetch('api/collections/'+collection)).json()).records.filter(r=>r.data[name]===value).length,{collection:collection.name,name,value});if(await page.locator('[data-record-id]').count()!==expected)throw Error('Record filter failed for '+name+'='+value);}await filter.selectOption('');}}
  await page.reload();await waitForWorkspace(page);await selectCollection(page,collection.name);await page.locator('[data-record-id]').first().waitFor({timeout:10000});const retained=await page.evaluate(async n=>(await(await fetch('api/collections/'+n)).json()).records,previous?.schema.collections[0].name||collection.name);if(saved&&!retained.some(r=>r.id===saved.id&&Object.entries(saved.data).every(([k,v])=>r.data[k]===v)))throw Error('Revision changed or lost a saved record');
  await page.locator('[data-record-id] button[data-action=edit]').first().click();await page.locator('#record-form').waitFor({state:'visible'});const editable=collection.fields.find(f=>['text','textarea','number'].includes(f.type));if(editable){const value=editable.type==='number'?126:'Edited QA '+editable.label;await page.locator('#record-form [name="'+editable.name+'"]').fill(String(value));await page.locator('#save-record').click();await page.waitForFunction(async({name,key,value})=>(await(await fetch('api/collections/'+name)).json()).records.some(r=>r.data[key]===value),{name:collection.name,key:editable.name,value},{timeout:10000});}else await page.locator('#save-record').click();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+8))throw Error('Desktop horizontal overflow');
  await page.setViewportSize({width:390,height:844});await page.reload();await waitForWorkspace(page);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+8))throw Error('Mobile horizontal overflow');await shot(page,'Mobile populated dashboard · 390px');
  await revealNavigationControl(page,'logout');
  await page.locator('#logout').click();await page.locator('#auth-form').waitFor({state:'visible',timeout:10000});await page.locator('#auth-email').fill(email);await page.locator('#auth-password').fill(password);await page.locator('#login').click();await waitForWorkspace(page,10000);await selectCollection(page,collection.name);await page.locator('[data-record-id]').first().waitFor();const totalBeforeDelete=(await page.evaluate(async()=>(await(await fetch('api/dashboard')).json()))).total;const beforeDelete=await page.evaluate(async n=>(await(await fetch('api/collections/'+n)).json()).records.length,collection.name);await page.locator('[data-record-id] button[data-action=delete]').first().click();await page.waitForFunction(async({name,count})=>(await(await fetch('api/collections/'+name)).json()).records.length===count-1,{name:collection.name,count:beforeDelete},{timeout:10000});const dashboard=await page.evaluate(async()=>(await(await fetch('api/dashboard')).json()));if(dashboard.total!==totalBeforeDelete-1)throw Error('Dashboard count failed after delete');if(errors.length)throw Error(errors.join('; '));return{passed:true,findings:[],...(capture?{_screenshots:screenshots,design_checks:designChecks}:{}),tested:['registration','login','collection navigation','UI create, edit and delete',...(sortedTable?['table sorting ascending/descending']:[]),'dashboard counts','persistent records after reload',...(previous?['saved records survive schema revision']:[]),'desktop1440px','mobile390px','logout'],at:new Date().toISOString()};
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}
}
function promptProject(p){return {schema:p.schema,files:components.source(designSystem.source(p.files))};}
const running=new Set();
async function run(job,callModel){
 writeJob(job);let previous,acquired=false,projectId=job.projectId;
 try{
  if(job.operation==='revise'||job.operation==='repair'){previous=runtime.getProject(projectId);if(running.has(projectId))throw Error('An app revision is already running');running.add(projectId);acquired=true;}else{projectId=String(job.projectName||'app').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,40)+'-'+crypto.randomBytes(4).toString('hex');}
  const useComponents=!previous||previous.ui_runtime==='kairoq-components-v1';const buildContract=CONTRACT+(useComponents?'\n'+components.contract:'');
  const dataBackend=previous?.data_backend||job.data_backend||'sqlite';if(dataBackend==='supabase'){const setup=await cloud.status();if(!setup.ready)throw Error(setup.error||'Supabase is not connected. Complete Build Studio setup first.');}
  if(job.operation==='repair'&&!job.reported_issue){try{await browserQA(projectId,previous,previous);job.status='complete';job.result={...previous,files:undefined,schema:undefined};job.result.summary='Diagnostics passed; no repair was needed.';return job;}catch(e){job.brief+='\nBrowser diagnostic: '+String(e.message).slice(0,1200);}}
  job.status='designing';writeJob(job);const designPlan=await designPipeline.plan(callModel,{brief:previous?(previous.brief+'\nRequested change: '+job.brief):job.brief,kind:'business app',style:job.style,previous:previous?.design_plan,existing:previous?.files});
  const version=previous?Math.max(...fs.readdirSync(path.join(runtime.ROOT,projectId,'versions')).map(Number).filter(Number.isFinite))+1:1;let prompt=buildContract+designPipeline.instructions(designPlan)+'\n'+design.guidance('business app',job.style,!!previous)+'\nAPP BRIEF: '+job.brief+'\nPROJECT NAME: '+job.projectName+'\nSTYLE: '+job.style;
  if(previous)prompt+='\nRevise this existing app following the requested change. Preserve existing collections/fields/types/options and all working auth/CRUD. New required fields need defaults. Existing project:'+JSON.stringify(promptProject(previous));
  let candidate,lastError;
  for(let attempt=0;attempt<3;attempt++){
   job.status=attempt?'repairing':'generating';job.attempt=attempt+1;writeJob(job);console.log('[fullstack-builder] '+job.status+' '+job.id+' attempt '+job.attempt);
   try{const result=await callModel({messages:[{role:'user',content:prompt}]});candidate=normalize(result);candidate.files=designSystem.apply(candidate.files,designPlan.style);if(useComponents)candidate.files=components.inject(candidate.files);if(previous)runtime.validateMigration(previous.schema,candidate.schema);job.status='testing';writeJob(job);const qa=await browserQA(projectId,candidate,previous,{capture:true});candidate.qa=qa;lastError=null;break;}catch(e){lastError=e;job.last_error=String(e.message||e).slice(0,1500);console.warn('[fullstack-builder] Check failed '+job.last_error);writeJob(job);prompt=buildContract+designPipeline.instructions(designPlan)+'\n'+design.guidance('business app',job.style,true)+'\nOriginal brief:'+job.brief+'\nRepair this failure from validation/browser QA: '+job.last_error+'\nReturn corrected complete schema and files. '+JSON.stringify(candidate?promptProject(candidate):previous?promptProject(previous):{});}
  }
  if(lastError)throw lastError;
  let evidence=[];for(let polish=0;polish<3;polish++){
   job.status='reviewing';writeJob(job);evidence=designPipeline.stripShots(candidate.qa);if(job.projectName==='PlanURstay Housing Desk'){const folder=path.join(__dirname,'public','generated','design-proof','pending');designPipeline.saveEvidence(folder,evidence);fs.writeFileSync(path.join(folder,'candidate.json'),JSON.stringify({schema:candidate.schema,files:candidate.files,design_plan:designPlan}));}const visual=await designPipeline.review(callModel,designPlan,evidence,candidate.qa.design_checks);candidate.qa.visual_review=visual;console.log('[fullstack-builder] VISUAL '+JSON.stringify(visual));if(visual.passed)break;
   if(polish===2)throw Error('Design review needs further refinement: '+visual.findings.map(f=>f.issue).join('; ').slice(0,900));
   job.status='polishing';writeJob(job);const polished=await callModel({messages:[{role:'user',content:buildContract+designPipeline.instructions(designPlan)+designPipeline.repairInstructions(visual)+'\nOriginal brief: '+job.brief+'\nCurrent complete project:'+JSON.stringify(promptProject(candidate))+'\nThis is visual-only refinement. Return ONLY JSON {files:{\"index.html\":complete HTML,\"styles.css\":complete CSS,\"app.js\":complete presentation JS}}. Do not return or change the schema; it is immutable and the trusted components render it.'}]});const refined=normalizePolish(candidate,polished);refined.files=designSystem.apply(refined.files,designPlan.style);if(useComponents)refined.files=components.inject(refined.files);runtime.validateMigration(candidate.schema,refined.schema);if(previous)runtime.validateMigration(previous.schema,refined.schema);try{refined.qa=await browserQA(projectId,refined,previous,{capture:true});candidate=refined;}catch(e){console.warn('[fullstack-builder] Polish changed functional layout; retaining working HTML/JS: '+e.message);const safe={...candidate,files:{...candidate.files,'styles.css':refined.files['styles.css']}};safe.qa=await browserQA(projectId,safe,previous,{capture:true});candidate=safe;}
  }
  candidate.design_plan=designPlan;writeVersion(projectId,version,candidate);designPipeline.saveEvidence(versionFolder(projectId,version),evidence);
  const metadata={id:projectId,project_name:candidate.project_name,summary:candidate.summary,brief:previous?.brief||job.brief,kind:'fullstack',ui_runtime:useComponents?'kairoq-components-v1':previous?.ui_runtime,design_plan:designPlan,style:designPlan.style,version,revisions:version-1,qa:candidate.qa,status:previous?.status==='live'?'live':'draft',generation_mode:'ai_generated_frontend',data_backend:dataBackend,backend:dataBackend==='supabase'?'Supabase Auth and PostgreSQL':'managed schema CRUD with SQLite',deployed_version:previous?.deployed_version||(previous?.status==='live'?previous.version:null),published_at:previous?.published_at,created_at:previous?.created_at||new Date().toISOString(),updated_at:new Date().toISOString(),preview_url:'/apps/'+projectId+'/preview/'+version+'/',live_url:'/apps/'+projectId+'/'};
  if(dataBackend==='supabase'&&!previous)await cloud.get().provision(projectId,candidate.schema,version);runtime.saveMetadata(metadata);job.status='complete';job.result=metadata;console.log('[fullstack-builder] RESULT '+JSON.stringify({job:job.id,id:projectId,version,qa:metadata.qa}));
 }catch(e){job.status='failed';job.error=String(e.message||e).slice(0,2000);console.error('[fullstack-builder] ERROR '+job.error);}finally{if(acquired)running.delete(projectId);job.finished_at=new Date().toISOString();writeJob(job);}return job;
}
function submit(input,callModel){const brief=String(input.brief||input.instruction||'').trim();if(brief.length<12||brief.length>6000)throw Error('Describe the app or change in 12–6000 characters');const job={id:crypto.randomUUID(),operation:input.repair?'repair':input.id?'revise':'build',reported_issue:!!input.reported_issue,data_backend:input.data_backend==='supabase'?'supabase':'sqlite',projectId:input.id||null,projectName:String(input.projectName||'Custom App').slice(0,100),brief,style:String(input.style||'editorial').slice(0,100),status:'queued',created_at:new Date().toISOString()};writeJob(job);run(job,callModel).catch(()=>{});return job;}
function listProjects(){if(!fs.existsSync(runtime.ROOT))return[];return fs.readdirSync(runtime.ROOT).flatMap(id=>{try{const p=runtime.getProject(id);delete p.files;return[p]}catch{return[]}}).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));}
async function publish(id){return require('./app-release').deploy(id);}
module.exports={submit,getJob,run,normalize,normalizePolish,browserQA,listProjects,publish};
