'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const builder=require('./app-builder'),runtime=require('./app-runtime'),web=require('./developer-agent');
const root=path.join(__dirname,'workspace'),marker=path.join(root,'.design-pipeline-smoke-v1.json'),progressFile=path.join(root,'.design-pipeline-progress-v1.json'),proof=path.join(__dirname,'public','generated','design-proof');
function expose(result){fs.mkdirSync(proof,{recursive:true});for(const [type,item]of [['app',result.app],['website',result.website]]){const folder=type==='app'?path.join(runtime.ROOT,item.id,'versions',String(item.version),'design-evidence'):path.join(root,'developer-projects',item.id,'design-evidence');if(fs.existsSync(folder))for(const name of fs.readdirSync(folder))if(/^\d+\.jpg$/.test(name))fs.copyFileSync(path.join(folder,name),path.join(proof,type+'-'+name));}const site=web.getProject(result.website.id);const embedded=web.assemble(site.files).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');fs.writeFileSync(path.join(proof,'website.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; frame-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>PlanURstay · Kairoq design showcase</title><style>html,body{margin:0;height:100%;background:#f5f2eb}iframe{border:0;width:100%;height:100%;display:block}</style></head><body><iframe title="Generated PlanURstay website" sandbox="allow-scripts" srcdoc="${embedded}"></iframe></body></html>`);result.website.showcase_url='/generated/design-proof/website.html';fs.writeFileSync(path.join(proof,'report.json'),JSON.stringify(result,null,2));}
async function run(model){if(fs.existsSync(marker)){expose(JSON.parse(fs.readFileSync(marker)));return;}let progress=fs.existsSync(progressFile)?JSON.parse(fs.readFileSync(progressFile)):{};const save=()=>fs.writeFileSync(progressFile,JSON.stringify(progress));
 if(!progress.app){const job={id:crypto.randomUUID(),operation:'build',projectName:'PlanURstay Housing Desk',style:'editorial',brief:'Build a polished corporate housing enquiry desk for PlanURstay operations. Users log in and manage saved enquiries with contact name, contact email, destination city, monthly budget, status (new, contacted, booked, closed) and follow-up date. Provide a calm editorial workspace with an intentional sidebar, clear list or table, concise dashboard, useful empty state and accessible record form. Use custom inline SVG/CSS architectural artwork only if useful. No fabricated customer claims, no payments or external integrations.',status:'queued',created_at:new Date().toISOString()};console.log('[design-smoke] app build started');await builder.run(job,model);if(job.status!=='complete')throw Error(job.error);await builder.publish(job.result.id);progress.app={id:job.result.id,version:job.result.version,url:'/apps/'+job.result.id+'/',visual_review:job.result.qa.visual_review,functional_qa:job.result.qa.tested};save();console.log('[design-smoke] APP '+JSON.stringify(progress.app));}
 if(!progress.website){console.log('[design-smoke] website build started');const site=await web.build({projectName:'PlanURstay Corporate Housing',kind:'website',style:'editorial',brief:'Create a polished corporate housing website for PlanURstay, operating in Canada and the USA since 2019. Offer furnished apartments, flexible stays, biweekly cleaning, 24/7 customer support and dedicated account managers. Address corporate relocation and insurance housing buyers. Use an elegant architectural inline SVG hero, clear service sections, useful FAQs and a working responsive mobile menu. Primary CTA scrolls to a contact section explaining how to enquire; do not invent contact details or pretend to send a form. No fabricated testimonials, statistics or certifications.'},model);if(!site.qa.passed||!site.qa.visual_review?.passed)throw Error('Website design QA did not pass');progress.website={id:site.id,preview_url:'/api/developer/preview/'+site.id,visual_review:site.qa.visual_review,functional_qa:site.qa.tested};save();console.log('[design-smoke] WEBSITE '+JSON.stringify(progress.website));}
 const result={passed:true,app:progress.app,website:progress.website,at:new Date().toISOString()};expose(result);fs.writeFileSync(marker,JSON.stringify(result));console.log('[design-smoke] RESULT '+JSON.stringify(result));}
module.exports={run};
