"use strict";
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const runtime=require('./housing-runtime');
const ROOT=path.join(__dirname,'workspace','developer-projects');
const ID='housing-enquiries';
const contract=`Build a real housing enquiry tracker, named PlanURstay Enquiries. Return ONLY JSON {project_name,summary,files:{"index.html":"...","styles.css":"...","app.js":"..."}}. Pure browser HTML/CSS/JS, no frameworks or external dependencies. Separate files with relative links. This is a FULL STACK app with an existing working backend. Use fetch('api/...') with same-origin credentials. NEVER localStorage for users or enquiries; backend is authoritative. Premium warm ivory/navy design, responsive dashboard, clear empty/loading/error states, labels and keyboard accessibility. Include working registration, login, logout, create/list/edit/delete enquiries, status controls and dashboard. Escape any user text using textContent or safe HTML escaping.
Backend API relative to app directory:
POST api/auth/register or api/auth/login {email,password} -> {user:{id,email}} and HttpOnly session cookie. Password minimum 10 chars. POST api/auth/logout {}. GET api/auth/me -> {user},401 if signed out.
GET api/enquiries -> {enquiries:[{id,name,email,city,arrival,departure,budget,status,notes,priority,created_at,updated_at}]}. POST api/enquiries {name,email,city,arrival,departure,budget,status,notes} -> {enquiry}. PATCH api/enquiries/ID accepts updated fields -> {enquiry}. DELETE api/enquiries/ID -> {ok:true}. GET api/dashboard -> {total,active,booked,pipeline_budget,urgent}. All data isolated to signed-in user. status one of new/contacted/quoted/booked/closed. dates YYYY-MM-DD, budget nonnegative.
Required functional DOM contract: #auth-form with #auth-email and #auth-password; two submit buttons #register and #login selecting register/login. Show auth form when signed out, app dashboard when signed in. #logout button. #enquiry-form inputs name attributes name,email,city,arrival,departure,budget,notes and select name=status. #save-enquiry submit button. Display each enquiry with data-enquiry-id=ID and buttons for edit and delete. #total-count contains dashboard total. Keep input form visible when signed in. Refresh data after mutations. Catch API errors and show readable messages. Call auth/me on load. Do not add priority controls in the first build; that is a later feature.
Return complete files, under 8500 output tokens. Do not claim mocked actions succeed.`;
function save(result,parse,folder){const p=typeof result==='string'?parse(result):result;const files=p.files;for(const name of ['index.html','styles.css','app.js']){if(typeof files?.[name]!=='string'||files[name].length>(150000))throw Error('Missing or oversized file '+name)}if(files['index.html'].length<350||files['styles.css'].length<500)throw Error('Incomplete app');new (require('vm').Script)(files['app.js']);fs.mkdirSync(folder,{recursive:true});for(const [name,code] of Object.entries(files)){if(!['index.html','styles.css','app.js'].includes(name))throw Error('Unsupported file');fs.writeFileSync(path.join(folder,name),code)}return files;}
async function handle(req,res){const match=/^\/apps\/([a-z0-9-]{5,85})\/(.*)$/.exec(req.url.split('?')[0]);if(!match)return false;const [,id,route]=match,folder=path.join(ROOT,id);if(!fs.existsSync(path.join(folder,'fullstack.json'))){res.writeHead(404);res.end('App not found');return true}if(route.startsWith('api/')){await runtime.handle(req,res,{root:ROOT,id,route:'/'+route.slice(4)});return true}const file=route||'index.html';if(!['index.html','styles.css','app.js'].includes(file)){res.writeHead(404);res.end('Not found');return true}res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/javascript','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'self'; base-uri 'self'; form-action 'self'"});res.end(fs.readFileSync(path.join(folder,file)));return true;}
async function browserTest(folder,{revise,callModel,parse}){
 const temp=fs.mkdtempSync(path.join(require('os').tmpdir(),'housing-qa-'));
 const server=http.createServer(async(req,res)=>{const route=req.url.split('?')[0];if(route.startsWith('/api/'))return runtime.handle(req,res,{root:temp,id:ID,route:route.slice(4)});const file=route==='/'?'index.html':route.slice(1);if(!['index.html','styles.css','app.js'].includes(file)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('html')?'text/html':file.endsWith('css')?'text/css':'application/javascript');res.end(fs.readFileSync(path.join(folder,file)));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';let browser;
 try{
  const {chromium}=require('playwright-core');browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
  await page.locator('#auth-email').fill('qa-'+crypto.randomBytes(3).toString('hex')+'@example.com');await page.locator('#auth-password').fill(crypto.randomBytes(12).toString('hex'));await page.locator('#register').click();await page.locator('#enquiry-form').waitFor({state:'visible',timeout:12000});
  await page.locator('#enquiry-form [name=name]').fill('QA Guest');await page.locator('#enquiry-form [name=email]').fill('guest@example.com');await page.locator('#enquiry-form [name=city]').fill('Toronto');await page.locator('#enquiry-form [name=budget]').fill('3500');await page.locator('#enquiry-form [name=arrival]').fill('2026-11-01');await page.locator('#enquiry-form [name=departure]').fill('2026-12-01');await page.locator('#save-enquiry').click();await page.locator('[data-enquiry-id]').first().waitFor({timeout:10000});
  const before=await page.evaluate(async()=>{const r=await fetch('api/enquiries');return r.json()});if(before.enquiries.length!==1)throw Error('Create did not persist');await page.reload();await page.locator('[data-enquiry-id]').first().waitFor({timeout:10000});
  if(revise){const files=Object.fromEntries(['index.html','styles.css','app.js'].map(n=>[n,fs.readFileSync(path.join(folder,n),'utf8')]));const instruction='Add an enquiry priority feature. Each enquiry supports priority normal/high/urgent already in backend. Add select name=priority to #enquiry-form and #priority-filter with values all/normal/high/urgent. Display priority badges on enquiry rows. Filter works client-side; edits PATCH priority to backend. Preserve ALL existing login, CRUD and dashboard features, IDs and API contract. Return complete JSON files. Existing files: '+JSON.stringify(files);save(await callModel({messages:[{role:'user',content:instruction}]}),parse,folder);await page.reload();await page.locator('[data-enquiry-id]').first().waitFor({timeout:10000});await page.locator('#enquiry-form [name=priority]').waitFor();await page.locator('#priority-filter').selectOption('urgent');await page.waitForTimeout(250);if(await page.locator('[data-enquiry-id]').count()!==0)throw Error('Priority filter failed');await page.locator('#priority-filter').selectOption('all');await page.locator('[data-enquiry-id]').first().waitFor();
   const after=await page.evaluate(async()=>{const r=await fetch('api/enquiries');return r.json()});if(JSON.stringify(before)!==JSON.stringify(after))throw Error('Revision changed saved data');
  }
  const api=await page.evaluate(async()=>{const r=await fetch('api/enquiries'),d=await r.json(),id=d.enquiries[0].id;await fetch('api/enquiries/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'booked',priority:'urgent'})});return(await fetch('api/dashboard')).json()});if(api.booked!==1||api.urgent!==1)throw Error('Status/priority dashboard failed');
  await page.setViewportSize({width:390,height:844});await page.reload();await page.locator('[data-enquiry-id]').first().waitFor({timeout:10000});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+8))throw Error('Mobile horizontal overflow');await page.locator('#logout').click();await page.locator('#auth-form').waitFor({state:'visible',timeout:10000});const protectedStatus=await page.evaluate(async()=> (await fetch('api/enquiries')).status);if(protectedStatus!==401)throw Error('Logout did not protect data');if(errors.length)throw Error(errors.join('; '));return{passed:true,tested:['registration','saved enquiry','reload persistence','AI priority revision preserves existing data','priority filter','status and dashboard','mobile 390px','logout protection'],errors};
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}
}
async function build(callModel,parse){const folder=path.join(ROOT,ID),metaPath=path.join(folder,'fullstack.json');if(fs.existsSync(metaPath)&&JSON.parse(fs.readFileSync(metaPath)).qa?.passed)return JSON.parse(fs.readFileSync(metaPath));if(!['index.html','styles.css','app.js'].every(n=>fs.existsSync(path.join(folder,n)))){const generated=await callModel({messages:[{role:'user',content:contract}]});save(generated,parse,folder);}console.log('[housing-app] Testing generated app and priority revision');const meta={id:ID,name:'PlanURstay Enquiries',generation_mode:'ai_generated_frontend',backend:'trusted SQLite housing runtime',created_at:new Date().toISOString(),url:'/apps/'+ID+'/',status:'testing'};fs.writeFileSync(metaPath,JSON.stringify(meta));try{meta.qa=await browserTest(folder,{revise:true,callModel,parse});meta.status='live';}catch(e){meta.qa={passed:false,error:e.message};meta.status='needs_repair';throw e}finally{fs.writeFileSync(metaPath,JSON.stringify(meta,null,2));}return meta;}
module.exports={handle,build,browserTest};