'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
async function run(model){
 const root=path.join(__dirname,'workspace'),marker=path.join(root,'.journey-smoke-v1.json'),progressFile=path.join(root,'.journey-smoke-progress-v1.json'),proof=path.join(__dirname,'public','generated','journey-proof');if(fs.existsSync(marker)){const saved=JSON.parse(fs.readFileSync(marker));const site=require('./developer-agent').getProject(saved.website.id);fs.mkdirSync(proof,{recursive:true});fs.writeFileSync(path.join(proof,'website.html'),require('./design-showcase').render(require('./developer-agent').assemble(site.files)));const origin=require('./app-release').publicOrigin();const qa=await require('./deployed-website-qa').verify(origin+saved.website.url);require('./design-pipeline').stripShots(qa);saved.website.deployed_qa=qa;fs.writeFileSync(path.join(proof,'report.json'),JSON.stringify(saved,null,2));console.log('[journey-smoke] Cached examples and public website reverified');return;}
 fs.mkdirSync(proof,{recursive:true});const progress=fs.existsSync(progressFile)?JSON.parse(fs.readFileSync(progressFile)):{};const save=()=>fs.writeFileSync(progressFile,JSON.stringify(progress));const builder=require('./app-builder'),web=require('./developer-agent'),pipeline=require('./design-pipeline');
 if(!progress.app){const jobs=path.join(root,'build-jobs');if(!progress.resume_job&&fs.existsSync(jobs)){const prior=fs.readdirSync(jobs).filter(n=>/^[a-f0-9-]{36}\.json$/.test(n)).map(n=>{try{return JSON.parse(fs.readFileSync(path.join(jobs,n)));}catch{return null;}}).filter(j=>j?.projectName==='PlanURstay Operations Journey'&&fs.existsSync(path.join(jobs,j.id+'.candidate.json'))).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];if(prior)progress.resume_job=prior.id;}console.log('[journey-smoke] Fresh two-collection app started');const job={id:crypto.randomUUID(),operation:'build',projectName:'PlanURstay Operations Journey',style:'editorial',brief:'Build a polished PlanURstay operations workspace with two collections: housing enquiries (contact name, email, city and status: new/contacted/booked/closed), and follow-up tasks (title, due date and priority: normal/urgent). Use the shared managed components for real login, saved records, dashboard, forms, search and collection navigation. Every collection must have clear new/edit/empty/populated views and readable mobile controls. Tailor headings to the selected collection. Use an elegant editorial identity, generous spacing and readable labels. Keep navigation and actions unambiguous. Do not add integrations or unsupported filters.',status:'queued',resume_job:progress.resume_job,created_at:new Date().toISOString()};await builder.run(job,model);if(job.status!=='complete'){if(job.checkpoint){progress.resume_job=job.checkpoint;save();}throw Error(job.error);}const released=await builder.publish(job.result.id);progress.app={id:released.id,url:released.live_url,qa:released.qa,deployed_qa:released.deployed_qa};save();console.log('[journey-smoke] APP '+JSON.stringify(progress.app));}
 if(!progress.website){console.log('[journey-smoke] Section-by-section website build started');const approved=web.listProjects().filter(p=>p.id.startsWith('planurstay-journey-website-')&&p.qa?.passed).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];const site=approved?web.getProject(approved.id):await web.build({projectName:'PlanURstay Journey Website',kind:'website',style:'editorial',brief:'Create a beautiful editorial corporate housing website for PlanURstay, serving Canada and the USA since 2019. Explain furnished apartments, flexible stays, biweekly cleaning, 24/7 support, dedicated account managers and corporate/insurance housing. Include architectural inline SVG artwork, service sections, working mobile menu and expandable FAQs. Use an enquiry CTA that scrolls to practical instructions; do not invent contact details or simulate form submission. All section text must be comfortably readable on mobile.'},model);if(!site.qa.passed)throw Error('Section-by-section website QA failed: '+JSON.stringify(site.qa.visual_review));const assembled=web.assemble(site.files);fs.writeFileSync(path.join(proof,'website.html'),require('./design-showcase').render(assembled));const origin=require('./app-release').publicOrigin();if(!origin)throw Error('No public origin available for website verification');const deployed=await require('./deployed-website-qa').verify(origin+'/generated/journey-proof/website.html');const shots=pipeline.stripShots(deployed);pipeline.saveEvidence(path.join(proof,'website'),shots);progress.website={id:site.id,url:'/generated/journey-proof/website.html',qa:site.qa,deployed_qa:deployed};save();console.log('[journey-smoke] WEBSITE '+JSON.stringify(progress.website));}
 const result={passed:true,...progress,at:new Date().toISOString()};fs.writeFileSync(marker,JSON.stringify(result));fs.writeFileSync(path.join(proof,'report.json'),JSON.stringify(result,null,2));console.log('[journey-smoke] RESULT '+JSON.stringify(result));
}
module.exports={run};
