'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const portable=require('./project-portability');
const active=new Set();
function client(repo,token=process.env.GITHUB_TOKEN,fetcher=fetch){
 if(!token)throw Error('Add GITHUB_TOKEN in Railway to enable project GitHub sync');if(!/^[\w.-]+\/[\w.-]+$/.test(repo||''))throw Error('Enter a repository as owner/name');
 return async(method,route,body,global=false)=>{const response=await fetcher('https://api.github.com'+(global?'':'/repos/'+repo)+route,{method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error('GitHub HTTP '+response.status+': '+String(data.message||'Request failed').slice(0,200));return data;};
}
const refPath=branch=>branch.split('/').map(encodeURIComponent).join('/');
function state(id){try{return JSON.parse(fs.readFileSync(path.join(portable.folder(id),'github-sync.json'),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
function save(id,data){const file=path.join(portable.folder(id),'github-sync.json'),tmp=file+'.'+crypto.randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,file);}
function status(id){portable.load(id);const s=state(id);return{configured:!!process.env.GITHUB_TOKEN,connected:!!s,...(s?{repository:s.repository,branch:s.branch,url:'https://github.com/'+s.repository+'/tree/'+s.branch,commit:s.commit,last_sync:s.at,local_changes:portable.fingerprint(portable.load(id))!==s.fingerprint}:{})};}
async function push(id,{repository,branch,create_name,apiFactory=client}={}){
 if(active.has(id))throw Error('Project sync is already running');active.add(id);
 try{
  const project=portable.load(id);if(!project.qa?.passed||!require('./benchmark-gates').validVisual(project.qa.visual_review))throw Error('GitHub export requires passing browser and AI screenshot review');
  const prior=state(id),hash=portable.fingerprint(project);repository=prior?.repository||repository||process.env.GITHUB_REPO;
  if(prior&&create_name)throw Error('This project is already connected');
  if(create_name){if(!/^[a-zA-Z0-9][\w.-]{1,79}$/.test(create_name))throw Error('Choose a safe new repository name');const created=await apiFactory(repository||'placeholder/project')('POST','/user/repos',{name:create_name,private:true,auto_init:true,description:'Generated by Kairoq: '+project.project_name},true);repository=created.full_name;branch=created.default_branch;}
  const api=apiFactory(repository),info=await api('GET','');branch=prior?.branch||branch||info.default_branch;if(!branch||branch.length>150||branch.includes('..')||/[~^:?*\[\\\s]/.test(branch))throw Error('Invalid GitHub branch');
  const ref=await api('GET','/git/ref/heads/'+refPath(branch)),head=ref.object.sha;
  if(prior&&head!==prior.commit)throw Error('GitHub changed since the last sync. Pull and test those changes before pushing');
  if(prior&&hash===prior.fingerprint)return{...status(id),unchanged:true};
  const parent=await api('GET','/git/commits/'+head),prefix='generated-projects/'+id+'/',bundle=portable.bundle(project),entries=[];let size=0;
  for(const [name,bytes]of Object.entries(bundle)){size+=bytes.length;if(size>100*1024*1024)throw Error('GitHub export exceeds 100MB');const blob=await api('POST','/git/blobs',{content:bytes.toString('base64'),encoding:'base64'});entries.push({path:prefix+name,mode:'100644',type:'blob',sha:blob.sha});}
  for(const name of prior?.files||[])if(!Object.hasOwn(bundle,name))entries.push({path:prefix+name,mode:'100644',type:'blob',sha:null});
  if(portable.fingerprint(portable.load(id))!==hash)throw Error('Project changed during export; retry after the build completes');
  const tree=await api('POST','/git/trees',{base_tree:parent.tree.sha,tree:entries}),commit=await api('POST','/git/commits',{message:'Kairoq: '+project.project_name+' '+(project.version?'v'+project.version:'revision '+project.revisions),tree:tree.sha,parents:[head]});await api('PATCH','/git/refs/heads/'+refPath(branch),{sha:commit.sha,force:false});
  save(id,{repository,branch,commit:commit.sha,fingerprint:hash,files:Object.keys(bundle),at:new Date().toISOString()});return status(id);
 }finally{active.delete(id);}
}
async function pull(id,{apiFactory=client,accept=portable.accept,callModel}={}){
 if(active.has(id))throw Error('Project sync is already running');active.add(id);
 try{
  const s=state(id);if(!s)throw Error('Export this project to GitHub first');const before=portable.load(id),hash=portable.fingerprint(before),api=apiFactory(s.repository),head=(await api('GET','/git/ref/heads/'+refPath(s.branch))).object.sha;
  if(head===s.commit)return{...status(id),unchanged:true};if(hash!==s.fingerprint)throw Error('Both Kairoq and GitHub changed. Resolve the conflict before syncing; neither version was overwritten');
  const commit=await api('GET','/git/commits/'+head),tree=await api('GET','/git/trees/'+commit.tree.sha+'?recursive=1');if(tree.truncated)throw Error('Repository tree is too large to sync safely');const prefix='generated-projects/'+id+'/',entries=tree.tree.filter(e=>e.path.startsWith(prefix));
  const blobs=new Map(entries.filter(e=>e.type==='blob'&&e.mode==='100644').map(e=>[e.path.slice(prefix.length),e]));
  async function read(name){const entry=blobs.get(name);if(!entry||entry.size>200000)throw Error('Missing or oversized project source: '+name);const blob=await api('GET','/git/blobs/'+entry.sha);if(blob.encoding!=='base64')throw Error('Unsupported GitHub blob encoding');const bytes=Buffer.from(blob.content.replace(/\s/g,''),'base64');if(bytes.length>200000)throw Error('Project source is too large');return bytes.toString('utf8');}
  const manifest=JSON.parse(await read('kairoq-project.json'));if(manifest.id!==id||manifest.kind!==before.kind||manifest.format!==1)throw Error('Remote project identity does not match');
  const files={};if(before.kind==='fullstack')for(const n of ['index.html','styles.css','app.js'])files[n]=await read('public/'+n);else for(const name of blobs.keys())if(['styles.css','app.js'].includes(name)||/^[a-z0-9][a-z0-9-]{0,48}\.html$/.test(name))files[name]=(await read(name)).replaceAll('assets/','/builder-assets/');
  for(const route of Object.keys(before.files).filter(n=>n.endsWith('.html')))if(!files[route])throw Error('GitHub revision removed an existing route');
  portable.assetLibraryCheck(files);
  // Asset bytes are immutable. Source/schema edits are accepted, silent binary replacement is not.
  const expected=portable.bundle(before);for(const [name,bytes]of Object.entries(expected))if(name.startsWith('assets/')||name.startsWith('workspace/builder-assets/')){const entry=blobs.get(name),sha=crypto.createHash('sha1').update(Buffer.from('blob '+bytes.length+'\0')).update(bytes).digest('hex');if(!entry||entry.sha!==sha)throw Error('GitHub asset bytes changed. Download replacements through the asset library before syncing');}
  const result=await accept(id,{...manifest,assets:before.assets,files},{callModel,expectedFingerprint:hash});
  save(id,{...s,commit:head,fingerprint:portable.fingerprint(result),files:[...blobs.keys()],at:new Date().toISOString()});return{...status(id),project:{...result,files:undefined,schema:undefined},message:'GitHub changes passed browser and visual review. Preview the new version before deploying.'};
 }finally{active.delete(id);}
}
async function autoPush(id){if(!state(id))return;try{await push(id);}catch(e){console.warn('[project-github] AUTO PUSH FAILED '+id+' '+e.message);}}
module.exports={client,push,pull,status,state,autoPush};
