'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const runtime=require('./app-runtime'),release=require('./app-release'),builder=require('./app-builder');
async function run(model){const marker=path.join(__dirname,'workspace','.release-repair-smoke-v1.json');if(fs.existsSync(marker))return;
 const originals=builder.listProjects().filter(p=>p.qa?.passed&&p.data_backend!=='supabase');if(!originals.length)throw Error('No tested app available for release QA');const source=runtime.getProject(originals[0].id);const id='release-qa-'+crypto.randomBytes(5).toString('hex');const qa={passed:true,tested:['copied verified source']};
 for(const version of [1,2,3]){const folder=path.join(runtime.ROOT,id,'versions',String(version));fs.mkdirSync(folder,{recursive:true});for(const[n,s]of Object.entries(source.files))fs.writeFileSync(path.join(folder,n),s+(n==='app.js'&&version===3?'\nthrow new Error("Kairoq intentional repair fixture");':''));fs.writeFileSync(path.join(folder,'manifest.json'),JSON.stringify({schema:source.schema,qa:version===3?{passed:false}:qa}));}
 runtime.saveMetadata({id,project_name:'Release Repair QA',kind:'fullstack',version:2,status:'draft',qa,data_backend:'sqlite',created_at:new Date().toISOString(),updated_at:new Date().toISOString()},runtime.ROOT);
 try{await release.deploy(id,{version:1});await release.deploy(id,{version:2});await release.deploy(id,{version:1,rollback:true});if(runtime.metadata(id).deployed_version!==1)throw Error('Rollback pointer failed');
 try{await release.deploy(id,{version:2,check:async()=>{throw Error('Simulated health failure')}});throw Error('Expected failed deployment')}catch(e){if(e.message==='Expected failed deployment')throw e;}if(runtime.metadata(id).deployed_version!==1)throw Error('Failed release replaced working app');
 const p=runtime.metadata(id);runtime.saveMetadata({...p,version:3,qa:{passed:false}});if(model){const job={id:crypto.randomUUID(),operation:'repair',projectId:id,projectName:'Release Repair QA',reported_issue:true,brief:'Repair the startup exception Kairoq intentional repair fixture appended to app.js. Remove this deliberate throw while preserving all auth, CRUD, fields, filters, styling and data. Return complete files and schema.',status:'queued',created_at:new Date().toISOString()};await builder.run(job,model);if(job.status!=='complete')throw Error(job.error);if(runtime.metadata(id).deployed_version!==1)throw Error('Repair silently changed live version');await release.deploy(id);}
 const result={passed:true,checks:['explicit deploy','versioned preview','rollback','failed deploy retains working app',...(model?['real AI repair','repair remains draft until deployed']:[])],at:new Date().toISOString()};fs.writeFileSync(marker,JSON.stringify(result));console.log('[release-smoke] RESULT '+JSON.stringify(result));
 }finally{fs.rmSync(path.join(runtime.ROOT,id),{recursive:true,force:true});}}
module.exports={run};
