'use strict';
const fs=require('fs'),path=require('path'),http=require('http');
async function run(){
 const marker=path.join(__dirname,'workspace','.studio-qa-v5.json');if(fs.existsSync(marker))return;
 const project={id:'qa-studio-app',project_name:'Studio QA App',kind:'fullstack',version:1,deployed_version:null,status:'draft',brief:'Test inventory app',preview_url:'/apps/qa-studio-app/',qa:{passed:true,tested:['login','CRUD'],findings:[]}};
 let polls=0,launched=false,browser;
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.url==='/api/developer/setup')return res.end(JSON.stringify({supabase:{ready:false,missing:['KAIROQ_SUPABASE_URL']}}));if(req.url.startsWith('/api/developer/releases/'))return res.end(JSON.stringify({versions:[{version:1,deployed:launched}],deployments:[]}));if(req.url==='/api/developer/rollback')return res.end(JSON.stringify({...project,status:'live',deployed_version:1}));if(req.url==='/api/developer/repair'){polls=0;return res.end(JSON.stringify({id:'qa-job',operation:'repair',status:'queued'}));}if(req.url==='/api/developer/projects')return res.end(JSON.stringify({projects:launched?[{...project,status:'live',deployed_version:1}]:[project]}));if(req.url==='/api/developer/build'||req.url==='/api/developer/revise'){polls=0;res.writeHead(202);return res.end(JSON.stringify({id:'qa-job',operation:'build',status:'queued'}));}if(req.url==='/api/developer/jobs/qa-job')return res.end(JSON.stringify(++polls>1?{status:'complete',result:project}:{id:'qa-job',status:'testing'}));if(req.url==='/api/developer/launch'){launched=true;return res.end(JSON.stringify({...project,status:'live',url:project.preview_url}));}const file=req.url==='/'?'public/build-studio.html':req.url.split('?')[0]==='/build-studio.js'?'public/build-studio.js':null;if(file){res.setHeader('Content-Type',file.endsWith('html')?'text/html':'application/javascript');return res.end(fs.readFileSync(path.join(__dirname,file)));}res.writeHead(404);res.end('{}');});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{browser=await require('playwright-core').chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#projects option[value="qa-studio-app"]').waitFor({state:'attached'});await page.locator('#projects').selectOption('qa-studio-app');if(!await page.locator('#launch').isVisible())throw Error('Saved app launch control missing');await page.locator('#projects').selectOption('');await page.locator('#name').fill('New Inventory');await page.locator('#brief').fill('Build an inventory tracker with login and saved stock records.');await page.locator('#build').click();await page.locator('#status').filter({hasText:'Checking login'}).waitFor({timeout:8000});await page.reload();await page.locator('#launch').waitFor({state:'visible',timeout:10000});await page.locator('#launch').click();await page.locator('#status').filter({hasText:'App launched'}).waitFor();await page.locator('#revision').fill('Add a category filter to the inventory list.');await page.locator('#revise').click();await page.locator('#status').filter({hasText:'Build passed'}).waitFor({timeout:12000});await page.locator('#rollback').click();await page.locator('#status').filter({hasText:'restored'}).waitFor();await page.locator('#repair').click();await page.locator('#status').filter({hasText:'Build passed'}).waitFor({timeout:12000});await page.locator('#projects').selectOption('');await page.locator('[data-example=inventory]').click();if(await page.locator('#name').inputValue()!=='Inventory manager')throw Error('Starter brief failed after project reset');for(const width of [1440,390]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Studio horizontal overflow at '+width);}if(errors.length)throw Error(errors.join('; '));const result={passed:true,checks:['saved project reopen','async build','refresh resumes job','launch','revision','repair','rollback','starter briefs after reset','desktop1440px','mobile390px'],at:new Date().toISOString()};fs.writeFileSync(marker,JSON.stringify(result));console.log('[studio-qa] RESULT '+JSON.stringify(result));}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
}
module.exports={run};
