'use strict';
const crypto=require('crypto');
function config(){return{url:String(process.env.KAIROQ_SUPABASE_URL||'').replace(/\/$/,''),publicKey:process.env.KAIROQ_SUPABASE_PUBLISHABLE_KEY||'',secret:process.env.KAIROQ_SUPABASE_SECRET_KEY||'',adminToken:process.env.KAIROQ_SUPABASE_ADMIN_TOKEN||'',encryption:process.env.APP_ENCRYPTION_KEY||''};}
function configured(){const c=config();return !!(c.url&&c.publicKey&&(c.secret||c.adminToken)&&c.encryption.length>=16);}
function client(c=config(),fetcher=fetch){
 if(!c.url||!c.publicKey||!(c.secret||c.adminToken)||c.encryption.length<16)throw Error('Supabase setup incomplete. Add the KAIROQ_SUPABASE variables and APP_ENCRYPTION_KEY in Railway.');
 const parsed=new URL(c.url);if(parsed.protocol!=='https:'&&!c.test)throw Error('Supabase URL must use HTTPS');
 const key=crypto.createHash('sha256').update(c.encryption).digest();
 async function request(route,{method='GET',body,token,admin=false,prefer}={}){const apiKey=admin?c.secret:c.publicKey;const headers={apikey:apiKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(prefer?{Prefer:prefer}:{})};if(admin&&!apiKey.startsWith('sb_secret_'))headers.Authorization='Bearer '+apiKey;let r;try{r=await fetcher(c.url+route,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});}catch{throw Object.assign(Error('Supabase is temporarily unreachable. Please retry.'),{status:503});}const data=await r.json().catch(()=>null);if(!r.ok){const missing=['42P01','PGRST205'].includes(data?.code);const error=Error(missing?'Run the Kairoq Supabase migration from Build Studio setup.':String(data?.msg||data?.error_description||data?.message||'Supabase request failed').slice(0,220));error.status=r.status>=500?503:r.status;throw error;}return data;}
 const name=id=>'kairoq_sb_'+id;
 function seal(id,session){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const raw=Buffer.from(JSON.stringify({id,access_token:session.access_token,refresh_token:session.refresh_token,expires_at:session.expires_at||Math.floor(Date.now()/1000)+(session.expires_in||3600)}));const encrypted=Buffer.concat([cipher.update(raw),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64url');}
 function unseal(id,value){try{const bytes=Buffer.from(value,'base64url'),decipher=crypto.createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));decipher.setAuthTag(bytes.subarray(12,28));const s=JSON.parse(Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString());return s.id===id&&s.access_token&&s.refresh_token?s:null;}catch{return null;}}
 function cookie(req,res,id,session){const value=session?seal(id,session):'';if(value.length>3800)throw Error('Supabase session exceeds cookie size');const item=name(id)+'='+value+'; HttpOnly; SameSite=Strict; Path=/apps/'+id+'/; Max-Age='+(session?604800:0)+(req.socket.encrypted||req.headers['x-forwarded-proto']==='https'?'; Secure':'');res.setHeader('Set-Cookie',item);}
 function read(req,id){const prefix=name(id)+'=';return unseal(id,String(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(prefix))?.slice(prefix.length)||'');}
 const refreshes=new Map();
 async function refresh(s){let p=refreshes.get(s.refresh_token);if(!p){p=request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:s.refresh_token}});refreshes.set(s.refresh_token,p);p.finally(()=>setTimeout(()=>refreshes.delete(s.refresh_token),10000).unref()).catch(()=>{});}return p;}
 async function session(req,res,id){let s=read(req,id);if(!s)return null;try{if(s.expires_at<Math.floor(Date.now()/1000)+60){s=await refresh(s);cookie(req,res,id,s);}let user;try{user=await request('/auth/v1/user',{token:s.access_token});}catch(e){if(e.status!==401)throw e;s=await refresh(s);cookie(req,res,id,s);user=await request('/auth/v1/user',{token:s.access_token});}return{...s,user};}catch(e){if(e.status>=500)throw e;cookie(req,res,id,null);return null;}}
 async function enroll(id,user){if(c.adminToken)return request('/rest/v1/rpc/kairoq_builder_enroll',{method:'POST',body:{admin_token:c.adminToken,target_app:id,target_user:user.id}});await request('/rest/v1/kairoq_app_members?on_conflict=app_id,user_id',{method:'POST',admin:true,prefer:'resolution=ignore-duplicates,return=minimal',body:{app_id:id,user_id:user.id}});}
 async function auth(req,res,id,route,body){if(route==='/auth/logout'){if(req.method!=='POST')throw Object.assign(Error('POST required'),{status:405});const s=read(req,id);try{if(s)await request('/auth/v1/logout?scope=local',{method:'POST',token:s.access_token});}catch(e){if(e.status>=500)throw e;}cookie(req,res,id,null);return{ok:true};}
 if(route==='/auth/me'){if(req.method!=='GET')throw Object.assign(Error('GET required'),{status:405});const s=await session(req,res,id);if(!s)throw Object.assign(Error('Sign in required'),{status:401});return{user:{id:s.user.id,email:s.user.email}};}
 if(!['/auth/register','/auth/login'].includes(route))throw Object.assign(Error('Endpoint not found'),{status:404});if(req.method!=='POST')throw Object.assign(Error('POST required'),{status:405});const b=await body(req),email=String(b.email||'').trim(),password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||email.length>160||password.length<10||password.length>200)throw Object.assign(Error('Use a valid email and a password of 10–200 characters'),{status:400});const s=await request(route==='/auth/register'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});if(!s.access_token)throw Object.assign(Error('Check your email to confirm your account, then sign in.'),{status:409,confirmationRequired:true});const user=await request('/auth/v1/user',{token:s.access_token});await enroll(id,user);cookie(req,res,id,s);return{user:{id:user.id,email:user.email}};}
 const map=r=>({id:r.id,collection:r.collection,data:r.payload,created_at:r.created_at,updated_at:r.updated_at});
 async function records(id,s,collection){return(await request('/rest/v1/kairoq_app_records?app_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+s.user.id+(collection?'&collection=eq.'+encodeURIComponent(collection):'')+'&select=*&order=created_at.desc&limit=10000',{token:s.access_token})||[]).map(map);}
 function filter(id,s,collection,rid){return'/rest/v1/kairoq_app_records?app_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+s.user.id+'&collection=eq.'+encodeURIComponent(collection)+(rid?'&id=eq.'+encodeURIComponent(rid):'');}
 async function save(id,s,collection,data,rid){const result=await request(rid?filter(id,s,collection,rid):'/rest/v1/kairoq_app_records',{method:rid?'PATCH':'POST',token:s.access_token,prefer:'return=representation',body:rid?{payload:data,updated_at:new Date().toISOString()}:{app_id:id,user_id:s.user.id,collection,payload:data}});if(!result?.[0])throw Object.assign(Error('Record not found'),{status:404});return map(result[0]);}
 async function remove(id,s,collection,rid){const result=await request(filter(id,s,collection,rid),{method:'DELETE',token:s.access_token,prefer:'return=representation'});if(!result?.length)throw Object.assign(Error('Record not found'),{status:404});return{ok:true};}
 async function provision(id,schema,version){if(c.adminToken)return request('/rest/v1/rpc/kairoq_builder_provision',{method:'POST',body:{admin_token:c.adminToken,target_app:id,app_schema:schema,app_version:version}});await request('/rest/v1/kairoq_apps?on_conflict=id',{method:'POST',admin:true,prefer:'resolution=merge-duplicates,return=minimal',body:{id,schema,deployed_version:version,updated_at:new Date().toISOString()}});}
 async function health(){if(c.adminToken){const result=await request('/rest/v1/rpc/kairoq_builder_health',{method:'POST',body:{admin_token:c.adminToken}});return{ready:result?.ready===true};}await request('/rest/v1/kairoq_apps?select=id&limit=0',{admin:true});await request('/rest/v1/kairoq_app_records?select=id&limit=0',{admin:true});await request('/rest/v1/kairoq_app_members?select=app_id&limit=0',{admin:true});return{ready:true};}
 return{auth,session,records,save,remove,provision,health,seal,unseal,read,cookie};
}
let cached;function get(){if(!cached)cached=client();return cached;}
async function status(){const required=['KAIROQ_SUPABASE_URL','KAIROQ_SUPABASE_PUBLISHABLE_KEY','APP_ENCRYPTION_KEY'];const missing=required.filter(n=>!process.env[n]);if(!process.env.KAIROQ_SUPABASE_SECRET_KEY&&!process.env.KAIROQ_SUPABASE_ADMIN_TOKEN)missing.push('KAIROQ_SUPABASE_ADMIN_TOKEN');if(missing.length)return{configured:false,ready:false,missing};try{return{configured:true,...await get().health(),missing:[]}}catch(e){return{configured:true,ready:false,missing:[],error:e.message}}}
module.exports={configured,client,get,status};
